# Generated by Django 6.0.2 on 2026-02-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Law',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('section_number', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('explanation', models.TextField()),
                ('punishment', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
