# Generated by Django 6.0.2 on 2026-03-24 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laws', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='law',
            old_name='title',
            new_name='file_name',
        ),
        migrations.RenameField(
            model_name='law',
            old_name='explanation',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='law',
            name='book_name',
        ),
        migrations.RemoveField(
            model_name='law',
            name='punishment',
        ),
        migrations.RemoveField(
            model_name='law',
            name='section_number',
        ),
    ]
