# Generated by Django 6.0.2 on 2026-03-26 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laws', '0002_rename_title_law_file_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='law',
            name='file_name',
        ),
        migrations.AddField(
            model_name='law',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='law',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='law',
            name='topic',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
